<?php 

	if ( !defined('ABSPATH') ) { 
		exit;
	}

	if( !class_exists('roark_visual_param') ) {
		

		class roark_visual_param {

			public function __construct() {
				add_action( 'wp_loaded', array($this, 'param_row_vc') );
				add_filter( 'vc_iconpicker-type-fontawesome', array($this, 'roark_font_linea' ));
			}

			public function param_row_vc() {

				if( function_exists('vc_add_param') ) {
					require_once PI_FILE_CORE . '/visual/params/param_vc_row.php';

					if( function_exists('vc_set_shortcodes_templates_dir') ) {
						$dir = get_stylesheet_directory() . '/core/visual/view/';
						vc_set_shortcodes_templates_dir($dir);
					}
				}
			}

			public function roark_font_linea($icons) {
				$linecons = array(
					array('icon-basic-accelerator'=> esc_html__('Accelerator', 'roark')),
					array('icon-basic-alarm'=> esc_html__('Alarm', 'roark')),
					array('icon-basic-anchor'=> esc_html__('Anchor', 'roark')),
					array('icon-basic-archive'=> esc_html__('Archive', 'roark')),
					array('icon-basic-archive-full'=> esc_html__('Archive Full', 'roark')),
					array('icon-basic-ban'=> esc_html__('Ban', 'roark')),
					array('icon-basic-battery-charge'=> esc_html__('Battery Charge', 'roark')),
					array('icon-basic-battery-empty'=> esc_html__('Battery Empty', 'roark')),
					array('icon-basic-battery-full'=> esc_html__('Battery Full', 'roark')),
					array('icon-basic-battery-half'=> esc_html__('Battery Half', 'roark')),
					array('icon-basic-bolt'=> esc_html__('Bolt', 'roark')),
					array('icon-basic-book'=> esc_html__('Book', 'roark')),
					array('icon-basic-book-pen'=> esc_html__('Book Pen', 'roark')),
					array('icon-basic-book-pencil'=> esc_html__('Book Pencil', 'roark')),
					array('icon-basic-bookmark'=> esc_html__('Bookmark', 'roark')),
					array('icon-basic-calculator'=> esc_html__('Calculator', 'roark')),
					array('icon-basic-calendar'=> esc_html__('Calendar', 'roark')),
					array('icon-basic-cards-diamonds'=> esc_html__('Cards Diamonds', 'roark')),
					array('icon-basic-cards-hearts'=> esc_html__('Cards Hearts', 'roark')),
					array('icon-basic-case'=> esc_html__('Case', 'roark')),
					array('icon-basic-chronometer'=> esc_html__('Chronometer', 'roark')),
					array('icon-basic-clessidre'=> esc_html__('Clessidre', 'roark')),
					array('icon-basic-clock'=> esc_html__('Clock', 'roark')),
					array('icon-basic-clockwise'=> esc_html__('Clockwise', 'roark')),
					array('icon-basic-cloud'=> esc_html__('Cloud', 'roark')),
					array('icon-basic-clubs'=> esc_html__('Clubs', 'roark')),
					array('icon-basic-compass'=> esc_html__('Compass', 'roark')),
					array('icon-basic-cup'=> esc_html__('Cup', 'roark')),
					array('icon-basic-diamonds'=> esc_html__('Diamonds', 'roark')),
					array('icon-basic-display'=> esc_html__('Display', 'roark')),
					array('icon-basic-download'=> esc_html__('Download', 'roark')),
					array('icon-basic-exclamation'=> esc_html__('Exclamation', 'roark')),
					array('icon-basic-eye'=> esc_html__('eye', 'roark')),
					array('icon-basic-eye-closed'=> esc_html__('Eye Closed', 'roark')),
					array('icon-basic-female'=> esc_html__('Female', 'roark')),
					array('icon-basic-flag1'=> esc_html__('Flag1', 'roark')),
					array('icon-basic-flag2'=> esc_html__('Flag2', 'roark')),
					array('icon-basic-floppydisk'=> esc_html__('Floppydisk', 'roark')),
					array('icon-basic-folder'=> esc_html__('Folder', 'roark')),
					array('icon-basic-folder-multiple'=> esc_html__('Folder Multiple', 'roark')),
					array('icon-basic-gear'=> esc_html__('Gear', 'roark')),
					array('icon-basic-geolocalize-01'=> esc_html__('Geolocalize 1', 'roark')),
					array('icon-basic-globe'=> esc_html__('Globe', 'roark')),
					array('icon-basic-gunsight'=> esc_html__('Gunsight', 'roark')),
					array('icon-basic-hammer'=> esc_html__('Hammer', 'roark')),
					array('icon-basic-headset'=> esc_html__('Headset', 'roark')),
					array('icon-basic-heart'=> esc_html__('Heart', 'roark')),
					array('icon-basic-heart-broken'=> esc_html__('Heart Broken', 'roark')),
					array('icon-basic-helm'=> esc_html__('Helm', 'roark')),
					array('icon-basic-home'=> esc_html__('Home', 'roark')),
					array('icon-basic-info'=> esc_html__('Info', 'roark')),
					array('icon-basic-ipod'=> esc_html__('Ipod', 'roark')),
					array('icon-basic-joypad'=> esc_html__('Joypad', 'roark')),
					array('icon-basic-key'=> esc_html__('Key', 'roark')),
					array('icon-basic-keyboard'=> esc_html__('Keyboard', 'roark')),
					array('icon-basic-laptop'=> esc_html__('Laptop', 'roark')),
					array('icon-basic-life-buoy'=> esc_html__('Life Buoy', 'roark')),
					array('icon-basic-lightbulb'=> esc_html__('Lightbulb', 'roark')),
					array('icon-basic-link'=> esc_html__('Link', 'roark')),
					array('icon-basic-lock'=> esc_html__('Lock', 'roark')),
					array('icon-basic-lock-open'=> esc_html__('Lock Open', 'roark')),
					array('icon-basic-magic-mouse'=> esc_html__('Magic Mouse', 'roark')),
					array('icon-basic-magnifier'=> esc_html__('Magnifier', 'roark')),
					array('icon-basic-magnifier-minus'=> esc_html__('Magnifier Minus', 'roark')),
					array('icon-basic-magnifier-plus'=> esc_html__('Magnifier Plus', 'roark')),
					array('icon-basic-mail'=> esc_html__('Mail', 'roark')),
					array('icon-basic-mail-multiple'=> esc_html__('Mail Multiple', 'roark')),
					array('icon-basic-mail-open'=> esc_html__('Mail Open', 'roark')),
					array('icon-basic-mail-open-text'=> esc_html__('Mail Open Text', 'roark')),
					array('icon-basic-male'=> esc_html__('Male', 'roark')),
					array('icon-basic-map'=> esc_html__('Map', 'roark')),
					array('icon-basic-message'=> esc_html__('Message', 'roark')),
					array('icon-basic-message-multiple'=> esc_html__('Message Multiple', 'roark')),
					array('icon-basic-message-txt'=> esc_html__('Message TXT', 'roark')),
					array('icon-basic-mixer2'=> esc_html__('Mixer2', 'roark')),
					array('icon-basic-mouse'=> esc_html__('Mouse', 'roark')),
					array('icon-basic-notebook'=> esc_html__('Notebook', 'roark')),
					array('icon-basic-notebook-pen'=> esc_html__('Notebook pen', 'roark')),
					array('icon-basic-notebook-pencil'=> esc_html__('Notebook pencil', 'roark')),
					array('icon-basic-paperplane'=> esc_html__('Paperplane', 'roark')),
					array('icon-basic-pencil-ruler'=> esc_html__('Pencil ruler', 'roark')),
					array('icon-basic-pencil-ruler-pen'=> esc_html__('Pencil ruler pen', 'roark')),
					array('icon-basic-photo'=> esc_html__('Photo', 'roark')),
					array('icon-basic-picture'=> esc_html__('Picture', 'roark')),
					array('icon-basic-picture-multiple'=> esc_html__('Picture multiple', 'roark')),
					array('icon-basic-pin1'=> esc_html__('Pin1', 'roark')),
					array('icon-basic-pin2'=> esc_html__('Pin2', 'roark')),
					array('icon-basic-postcard'=> esc_html__('Postcard', 'roark')),
					array('icon-basic-postcard-multiple'=> esc_html__('Postcard multiple', 'roark')),
					array('icon-basic-printer'=> esc_html__('Printer', 'roark')),
					array('icon-basic-question'=> esc_html__('Question', 'roark')),
					array('icon-basic-rss'=> esc_html__('Rss', 'roark')),
					array('icon-basic-server'=> esc_html__('Server', 'roark')),
					array('icon-basic-server2'=> esc_html__('Server2', 'roark')),
					array('icon-basic-server-cloud'=> esc_html__('Server cloud', 'roark')),
					array('icon-basic-server-download'=> esc_html__('Server download', 'roark')),
					array('icon-basic-server-upload'=> esc_html__('Server upload', 'roark')),
					array('icon-basic-settings'=> esc_html__('Settings', 'roark')),
					array('icon-basic-share'=> esc_html__('Share', 'roark')),
					array('icon-basic-sheet'=> esc_html__('Sheet', 'roark')),
					array('icon-basic-sheet-multiple'=> esc_html__('Sheet multiple', 'roark')),
					array('icon-basic-sheet-pen'=> esc_html__('Sheet pen', 'roark')),
					array('icon-basic-sheet-pencil'=> esc_html__('Sheet pencil', 'roark')),
					array('icon-basic-sheet-txt'=> esc_html__('Sheet txt', 'roark')),
					array('icon-basic-signs'=> esc_html__('Signs', 'roark')),
					array('icon-basic-smartphone'=> esc_html__('Smartphone', 'roark')),
					array('icon-basic-spades'=> esc_html__('Spades', 'roark')),
					array('icon-basic-spread'=> esc_html__('Spread', 'roark')),
					array('icon-basic-spread-bookmark'=> esc_html__('Spread bookmark', 'roark')),
					array('icon-basic-spread-text'=> esc_html__('Spread text', 'roark')),
					array('icon-basic-spread-text-bookmark'=> esc_html__('Spread text bookmark', 'roark')),
					array('icon-basic-star'=> esc_html__('Star', 'roark')),
					array('icon-basic-tablet'=> esc_html__('Tablet', 'roark')),
					array('icon-basic-target'=> esc_html__('Target', 'roark')),
					array('icon-basic-todo'=> esc_html__('Todo', 'roark')),
					array('icon-basic-todo-pen'=> esc_html__('Todo pen', 'roark')),
					array('icon-basic-todo-pencil'=> esc_html__('Todo pencil', 'roark')),
					array('icon-basic-todo-txt'=> esc_html__('Todo txt', 'roark')),
					array('icon-basic-todolist-pen'=> esc_html__('Todolist pen', 'roark')),
					array('icon-basic-todolist-pencil'=> esc_html__('Todolist pencil', 'roark')),
					array('icon-basic-trashcan'=> esc_html__('Trashcan', 'roark')),
					array('icon-basic-trashcan-full'=> esc_html__('Trashcan full', 'roark')),
					array('icon-basic-trashcan-refresh'=> esc_html__('Trashcan refresh', 'roark')),
					array('icon-basic-trashcan-remove'=> esc_html__('Trashcan remove', 'roark')),
					array('icon-basic-upload'=> esc_html__('Upload', 'roark')),
					array('icon-basic-usb'=> esc_html__('Usb', 'roark')),
					array('iconbasic-video-'=> esc_html__('Video', 'roark')),
					array('icon-basic-watch'=> esc_html__('Watch', 'roark')),
					array('icon-basic-webpage'=> esc_html__('Webpage', 'roark')),
					array('icon-basic-webpage-img-txt'=> esc_html__('Webpage img txt', 'roark')),
					array('icon-basic-webpage-multiple'=> esc_html__('Webpage multiple', 'roark')),
					array('icon-basic-webpage-txt'=> esc_html__('Webpage txt', 'roark')),
					array('icon-basic-world'=> esc_html__('World', 'roark')),
					array('icon-ecommerce-bag'=> esc_html__('Bag', 'roark')),
					array('icon-ecommerce-bag-check'=> esc_html__('Bag check', 'roark')),
					array('icon-ecommerce-bag-cloud'=> esc_html__('Bag cloud', 'roark')),
					array('icon-ecommerce-bag-download'=> esc_html__('Bag download', 'roark')),
					array('icon-ecommerce-bag-minus'=> esc_html__('Bag minus', 'roark')),
					array('icon-ecommerce-bag-plus'=> esc_html__('Heart', 'roark')),
					array('icon-ecommerce-bag-refresh'=> esc_html__('Bag refresh', 'roark')),
					array('icon-ecommerce-bag-remove'=> esc_html__('Bag remove', 'roark')),
					array('icon-ecommerce-bag-search'=> esc_html__('Bag search', 'roark')),
					array('icon-ecommerce-bag-upload'=> esc_html__('Bag upload', 'roark')),
					array('icon-ecommerce-banknote'=> esc_html__('Banknote', 'roark')),
					array('icon-ecommerce-banknotes'=> esc_html__('Banknotes', 'roark')),
					array('icon-ecommerce-basket'=> esc_html__('Basket', 'roark')),
					array('icon-ecommerce-basket-check'=> esc_html__('Basket check', 'roark')),
					array('icon-ecommerce-basket-cloud'=> esc_html__('Basket cloud', 'roark')),
					array('icon-ecommerce-basket-download'=> esc_html__('Basket download', 'roark')),
					array('icon-ecommerce-basket-minus'=> esc_html__('Basket minus', 'roark')),
					array('icon-ecommerce-basket-plus'=> esc_html__('Basket plus', 'roark')),
					array('icon-ecommerce-basket-refresh'=> esc_html__('Basket refresh', 'roark')),
					array('icon-ecommerce-basket-remove'=> esc_html__('Basket remove', 'roark')),
					array('icon-ecommerce-basket-search'=> esc_html__('Basket search', 'roark')),
					array('icon-ecommerce-basket-upload'=> esc_html__('Basket upload', 'roark')),
					array('icon-ecommerce-bath'=> esc_html__('Bath', 'roark')),
					array('icon-ecommerce-cart'=> esc_html__('Cart', 'roark')),
					array('icon-ecommerce-cart-check'=> esc_html__('Cart check', 'roark')),
					array('icon-ecommerce-cart-cloud'=> esc_html__('Cart cloud', 'roark')),
					array('icon-ecommerce-cart-content'=> esc_html__('Cart content', 'roark')),
					array('icon-ecommerce-cart-download'=> esc_html__('Cart download', 'roark')),
					array('icon-ecommerce-cart-minus'=> esc_html__('Cart minus', 'roark')),
					array('icon-ecommerce-cart-plus'=> esc_html__('Cart plus', 'roark')),
					array('icon-ecommerce-cart-refresh'=> esc_html__('Cart refresh', 'roark')),
					array('icon-ecommerce-cart-remove'=> esc_html__('Cart remove', 'roark')),
					array('icon-ecommerce-cart-search'=> esc_html__('Cart Search', 'roark')),
					array('icon-ecommerce-cart-upload'=> esc_html__('Cart Upload', 'roark')),
					array('icon-ecommerce-cent'=> esc_html__('Cent', 'roark')),
					array('icon-ecommerce-colon'=> esc_html__('Colon', 'roark')),
					array('icon-ecommerce-creditcard'=> esc_html__('Creditcard', 'roark')),
					array('icon-ecommerce-diamond'=> esc_html__('Diamond', 'roark')),
					array('icon-ecommerce-dollar'=> esc_html__('Dollar', 'roark')),
					array('icon-ecommerce-euro'=> esc_html__('Euro', 'roark')),
					array('icon-ecommerce-franc'=> esc_html__('Franc', 'roark')),
					array('icon-ecommerce-gift'=> esc_html__('Gift', 'roark')),
					array('icon-ecommerce-graph1'=> esc_html__('Graph1', 'roark')),
					array('icon-ecommerce-graph2'=> esc_html__('Graph2', 'roark')),
					array('icon-ecommerce-graph3'=> esc_html__('Graph3', 'roark')),
					array('icon-ecommerce-graph-decrease'=> esc_html__('Graph decrease', 'roark')),
					array('icon-ecommerce-graph-increase'=> esc_html__('Graph increase', 'roark')),
					array('icon-ecommerce-guarani'=> esc_html__('Guarani', 'roark')),
					array('icon-ecommerce-kips'=> esc_html__('Kips', 'roark')),
					array('icon-ecommerce-lira'=> esc_html__('Lira', 'roark')),
					array('icon-ecommerce-megaphone'=> esc_html__('Megaphone', 'roark')),
					array('icon-ecommerce-money'=> esc_html__('Money', 'roark')),
					array('icon-ecommerce-naira'=> esc_html__('Maira', 'roark')),
					array('icon-ecommerce-pesos'=> esc_html__('Pesos', 'roark')),
					array('icon-ecommerce-pound'=> esc_html__('Pound', 'roark')),
					array('icon-ecommerce-receipt'=> esc_html__('Receipt', 'roark')),
					array('icon-ecommerce-receipt-bath'=> esc_html__('Receipt bath', 'roark')),
					array('icon-ecommerce-receipt-cent'=> esc_html__('Receipt cent', 'roark')),
					array('icon-ecommerce-receipt-dollar'=> esc_html__('Receipt dollar', 'roark')),
					array('icon-ecommerce-receipt-euro'=> esc_html__('Receipt euro', 'roark')),
					array('icon-ecommerce-receipt-franc'=> esc_html__('Receipt franc', 'roark')),
					array('icon-ecommerce-receipt-guarani'=> esc_html__('Receipt guarani', 'roark')),
					array('icon-ecommerce-receipt-kips'=> esc_html__('Receipt kips', 'roark')),
					array('icon-ecommerce-receipt-lira'=> esc_html__('Receipt lira', 'roark')),
					array('icon-ecommerce-receipt-naira'=> esc_html__('Receipt naira', 'roark')),
					array('icon-ecommerce-receipt-pesos'=> esc_html__('Receipt pesos', 'roark')),
					array('icon-ecommerce-receipt-pound'=> esc_html__('Receipt pound', 'roark')),
					array('icon-ecommerce-receipt-rublo'=> esc_html__('Receipt rublo', 'roark')),
					array('icon-ecommerce-receipt-rupee'=> esc_html__('Receipt rupee', 'roark'))
				);

				return $linecons;
			}
		}

		new roark_visual_param();
	}
